language: node_js
node_js: node

script:
  # will run `npm ci` automatically here
  - npm run lint

notifications:
  email: false

deploy:
  - provider: npm
    email: 'devops@oceanprotocol.com'
    api_key: ${NPM_TOKEN}
    skip_cleanup: true
    on:
      tags: true
